/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import control.FNegocio;
import control.INegocio;
import dominio.Categoria;
import dominio.DetalleIngrediente;
import dominio.Ingrediente;
import dominio.Producto;
import dominio.ProductoListo;
import dominio.ProductoPreparado;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fernanda Miranda
 */
public class RegistrarProducto extends javax.swing.JFrame {

    private ConsultarProductos busqueda;
    private INegocio fNegocio;
    private List<Categoria> categorias;
    private Producto productoActualizado;
    private List<Ingrediente> ingredientes;
    private List<DetalleIngrediente> ingredientesAgregados;
    private DefaultListModel modeloIngredientes;
    private final INegocio fnegocios;

    /**
     * Creates new form RegistrarPedido
     */
    public RegistrarProducto() {
        initComponents();
        this.setTitle("FrmRegistrarPedido");
        this.setLocationRelativeTo(null);
        this.fNegocio = new FNegocio();
        this.categorias = new ArrayList<>();
        this.ingredientes = new ArrayList<>();
        this.ingredientesAgregados = new ArrayList<>();
        this.modeloIngredientes = new DefaultListModel();
        this.jListIngredientes.setModel(modeloIngredientes);
        this.fnegocios = new FNegocio();
        this.setCategorias();
        this.obtenerIngredientes();
        this.cargarTabla();
    }

    private void setCategorias() {
        //SANDWICHES, LICUADOS, JUGO, CAFES, FRAPPES, SNACKS, POSTRES
        categorias.add(Categoria.SANDWICHES);
        categorias.add(Categoria.LICUADOS);
        categorias.add(Categoria.JUGOS);
        categorias.add(Categoria.CAFES);
        categorias.add(Categoria.FRAPPES);
        categorias.add(Categoria.SNACKS);
        categorias.add(Categoria.POSTRES);
        this.cboxCategoria.addItem(categorias.get(0));
        this.cboxCategoria.addItem(categorias.get(1));
        this.cboxCategoria.addItem(categorias.get(2));
        this.cboxCategoria.addItem(categorias.get(3));
        this.cboxCategoria.addItem(categorias.get(4));
        this.cboxCategoria.addItem(categorias.get(5));
        this.cboxCategoria.addItem(categorias.get(6));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cboxCategoria = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnHGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cboxTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIngredientes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListIngredientes = new javax.swing.JList<>();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 99, 57)));

        jPanel2.setBackground(new java.awt.Color(245, 235, 220));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 221, 221)));
        jPanel2.setPreferredSize(new java.awt.Dimension(426, 70));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(230, 99, 57));
        jLabel6.setText("Registrar Producto");

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 23)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dona32px.png"))); // NOI18N
        jLabel7.setText("100%");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Categoría");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Precio");

        txtName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        cboxCategoria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtPrecio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(230, 99, 57));
        jButton1.setText("Cancelar");

        btnHGuardar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnHGuardar.setForeground(new java.awt.Color(230, 99, 57));
        btnHGuardar.setText("Guardar");
        btnHGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHGuardarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Tipo");

        cboxTipo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PREPARADO", "LISTO" }));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Cantidad");

        txtCantidad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tblIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblIngredientes);

        jScrollPane2.setViewportView(jListIngredientes);

        btnAgregar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(230, 99, 57));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(txtPrecio)
                                    .addComponent(txtCantidad)))
                            .addComponent(btnAgregar))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(cboxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(cboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 128, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHGuardar)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cboxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHGuardar)
                    .addComponent(jButton1))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHGuardarActionPerformed
        if (productoActualizado == null) {
            addProducto();
        } else {
            updateProducto();
        }
    }//GEN-LAST:event_btnHGuardarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        this.cargarIngrediente();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void agregarIngredientesActualizado() {
        for (DetalleIngrediente dIngrediente : productoActualizado.getDetalleIngredientes()) {
            this.agregarIngrediente(dIngrediente);
        }
    }

    private void cargarIngrediente() {
        int fila = this.tblIngredientes.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un Ingrediente.",
                    "Precaución", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) this.tblIngredientes.getModel();
            Long idIngrediente = (Long) modelo.getValueAt(fila, 0);
            Ingrediente ingrediente = fnegocios.obtenerIngredientePorId(idIngrediente);
            if (ingrediente != null) {
                /*
                    CAMBIAR TOSTRING DE INGREDIENTE PARA QUE SALGA BIEN EN LA LISTA
                    O CAMBIAR MODELO PARA QUE SEA UN STRING, CREAR UN METODO PARA BUSCAR Y LUEGO HACER CUALQUIER OTRA OPCIÓN.
                 */
                agregarIngrediente(crearDetalleIngredientes(ingrediente));
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el producto.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void agregarIngrediente(DetalleIngrediente ingrediente) {
        this.ingredientesAgregados.add(ingrediente);
        this.modeloIngredientes.addElement(ingrediente.getIngrediente());
    }

    private void obtenerIngredientes() {
        this.ingredientes = fNegocio.obtenerIngredientes();
    }

    private void cargarTabla() {
        if (ingredientes != null) {
            DefaultTableModel modelo = (DefaultTableModel) tblIngredientes.getModel();
            modelo.setRowCount(0);
            for (Ingrediente c : ingredientes) {
                modelo.addRow(this.toArray(c));
            }
        } else {
            JOptionPane.showMessageDialog(this, "Sin resultados.",
                    "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private Object[] toArray(Ingrediente p) {
        return new Object[]{
            p.getId(),
            p.getNombre()
        };
    }

    public void cargarProducto(Producto producto) {
        this.productoActualizado = producto;
        this.txtName.setText(producto.getNombre());
        this.cboxCategoria.setSelectedItem(producto.getCategoria());
        this.txtPrecio.setText(producto.getPrecio().toString());
        this.cboxTipo.setEnabled(false);
        this.txtCantidad.setText(producto.getCantidad().toString());
        this.agregarIngredientesActualizado();
    }

    private void addProducto() {
        String nombre = this.txtName.getText();
        Categoria categoria = (Categoria) this.cboxCategoria.getSelectedItem();
        float precio = Float.parseFloat(this.txtPrecio.getText());
        String tipo = this.cboxTipo.getSelectedItem().toString();
        int cantidad = Integer.valueOf(this.txtCantidad.getText());
        Producto producto;
        if (categoria.equals("PREPARADO")) {
            producto = new ProductoPreparado(tipo, nombre, precio, cantidad, categoria);
        } else {
            producto = new ProductoListo(nombre, precio, cantidad, categoria);
        }
        addProductoToDetalle(producto);
        producto.setDetalleIngredientes(ingredientesAgregados);
        if (fNegocio.guardarProducto(producto)) {
            JOptionPane.showMessageDialog(rootPane, "Producto guardado");
            this.ingredientesAgregados = new ArrayList<>();
            this.regresarBusquedaProducto();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error al guardar");
        }
    }

    private void regresarBusquedaProducto() {
        this.busqueda = new ConsultarProductos();
        busqueda.setVisible(true);
        this.dispose();
    }

    private void addProductoToDetalle(Producto producto) {
        for (DetalleIngrediente ia : ingredientesAgregados) {
            ia.setProducto(producto);
        }
    }

    private DetalleIngrediente crearDetalleIngredientes(Ingrediente ingrediente) {
        DetalleIngrediente dt = new DetalleIngrediente();
        dt.setIngrediente(ingrediente);
        return dt;
    }

    private void updateProducto() {
        String nombre = this.txtName.getText();
        Categoria categoria = (Categoria) this.cboxCategoria.getSelectedItem();
        float precio = Float.parseFloat(this.txtPrecio.getText());
        int cantidad = Integer.valueOf(this.txtCantidad.getText());
        this.productoActualizado.setNombre(nombre);
        this.productoActualizado.setCategoria(categoria);
        this.productoActualizado.setPrecio(precio);
        this.productoActualizado.setCantidad(cantidad);
        addProductoToDetalle(productoActualizado);
        this.productoActualizado.setDetalleIngredientes(ingredientesAgregados);
        System.out.println(ingredientesAgregados);
        if (fNegocio.actualizarProducto(productoActualizado)) {
            this.productoActualizado = null;
            JOptionPane.showMessageDialog(rootPane, "Producto actualizado");
            this.regresarBusquedaProducto();

        } else {
            JOptionPane.showMessageDialog(rootPane, "Error al actualizar producto");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnHGuardar;
    private javax.swing.JComboBox<Categoria> cboxCategoria;
    private javax.swing.JComboBox<String> cboxTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jListIngredientes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblIngredientes;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
